#!/bin/sh /etc/rc.common

START=60

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1



stop() {
	service_stop /usr/bin/diyiotserver
}

start() {
export TERM='xterm'

	diyiotserver=50001
	service_start  /usr/bin/diyiotserver -S 127.0.0.1:$diyiotserver -t /root/DIYiotClient-master 
}
