#!/bin/sh /etc/rc.common

START=60

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1


. /root/admin/applconfig.sh

stop() {
	service_stop /usr/bin/socat
}

start() {
export TERM='xterm'

	DEV=$DEV
	dataport=$dataport
	BAUD=$BAUD
        stty -F $DEV $BAUD                                
        service_start /usr/bin/socat tcp-l:$dataport,reuseaddr,fork file:$DEV,nonblock,raw,echo=0,waitlock=/var/run/tty,b$BAUD
}
                                        
